// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sumcloudformation

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	"sync"
)

// Ensure, that CloudFormationInterfaceMock does implement CloudFormationInterface.
// If this is not the case, regenerate this file with moq.
var _ CloudFormationInterface = &CloudFormationInterfaceMock{}

// CloudFormationInterfaceMock is a mock implementation of CloudFormationInterface.
//
//     func TestSomethingThatUsesCloudFormationInterface(t *testing.T) {
//
//         // make and configure a mocked CloudFormationInterface
//         mockedCloudFormationInterface := &CloudFormationInterfaceMock{
//             ListStacksFunc: func(ctx context.Context, params *cloudformation.ListStacksInput, optFns ...func(*cloudformation.Options)) (*cloudformation.ListStacksOutput, error) {
// 	               panic("mock out the ListStacks method")
//             },
//         }
//
//         // use mockedCloudFormationInterface in code that requires CloudFormationInterface
//         // and then make assertions.
//
//     }
type CloudFormationInterfaceMock struct {
	// ListStacksFunc mocks the ListStacks method.
	ListStacksFunc func(ctx context.Context, params *cloudformation.ListStacksInput, optFns ...func(*cloudformation.Options)) (*cloudformation.ListStacksOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListStacks holds details about calls to the ListStacks method.
		ListStacks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *cloudformation.ListStacksInput
			// OptFns is the optFns argument value.
			OptFns []func(*cloudformation.Options)
		}
	}
	lockListStacks sync.RWMutex
}

// ListStacks calls ListStacksFunc.
func (mock *CloudFormationInterfaceMock) ListStacks(ctx context.Context, params *cloudformation.ListStacksInput, optFns ...func(*cloudformation.Options)) (*cloudformation.ListStacksOutput, error) {
	if mock.ListStacksFunc == nil {
		panic("CloudFormationInterfaceMock.ListStacksFunc: method is nil but CloudFormationInterface.ListStacks was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *cloudformation.ListStacksInput
		OptFns []func(*cloudformation.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockListStacks.Lock()
	mock.calls.ListStacks = append(mock.calls.ListStacks, callInfo)
	mock.lockListStacks.Unlock()
	return mock.ListStacksFunc(ctx, params, optFns...)
}

// ListStacksCalls gets all the calls that were made to ListStacks.
// Check the length with:
//     len(mockedCloudFormationInterface.ListStacksCalls())
func (mock *CloudFormationInterfaceMock) ListStacksCalls() []struct {
	Ctx    context.Context
	Params *cloudformation.ListStacksInput
	OptFns []func(*cloudformation.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *cloudformation.ListStacksInput
		OptFns []func(*cloudformation.Options)
	}
	mock.lockListStacks.RLock()
	calls = mock.calls.ListStacks
	mock.lockListStacks.RUnlock()
	return calls
}
